import React, { createContext, useContext, useState, useEffect } from 'react';

export type Theme = 'light' | 'dark';
export type Language = 'zh' | 'en' | 'zh-TW' | 'ja' | 'ko' | 'fr' | 'de' | 'es' | 'it' | 'pt' | 'ru' | 'ar' | 'hi' | 'th' | 'vi' | 'tr';

interface ThemeContextType {
  theme: Theme;
  setTheme: (theme: Theme) => void;
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const translations = {
  zh: {
    'app.title': '得到字幕',
    'nav.settings': 'API 设置',
    'source.select': '选择音视频来源',
    'tab.local': '本地文件',
    'tab.online': '在线音频URL',
    'options.title': '处理选项',
    'options.source': '源语言',
    'options.translate': '翻译字幕',
    'options.target': '目标语言',
    'button.generate': '生成字幕',
    'button.processing': '处理中...',
    'config.needed': '需要配置 API',
    'config.message': '请配置语音识别和翻译服务的 API 密钥以开始使用。',
    'config.setup': '立即配置',
    'usage.title': '使用说明',
    'usage.quickstart': '快速开始',
    'usage.features': '功能特性',
    'usage.step1': '点击右上角「API 设置」配置语音识别和翻译API',
    'usage.step2': '上传音频或视频文件，或输入在线音频URL',
    'usage.step3': '选择源语言和翻译选项',
    'usage.step4': '点击「生成字幕」开始处理',
    'usage.step5': '在预览区域编辑字幕内容（可选）',
    'usage.step6': '下载生成的SRT文件',
    'feature.audio': '🎵 支持多种音频格式：MP3、WAV、M4A、FLAC、OGG',
    'feature.video': '🎬 支持多种视频格式：MP4、AVI、MOV、MKV、WMV',
    'feature.online': '🔗 支持在线音频URL处理',
    'feature.preview': '📝 完整字幕预览和编辑功能',
    'feature.translate': '🌐 支持多种语言翻译',
    'feature.config': '⚙️ 灵活的API配置管理',
    'feature.download': '💾 支持SRT格式文件下载',
    'footer.copyright': '得到字幕 ©{year} - veeblue',
    'upload.title': '点击或拖拽文件到此区域上传',
    'upload.support': '支持单个文件上传，支持拖拽上传',
    'upload.select': '重新选择文件',
    'upload.error': '上传错误',
    'upload.format': '支持的格式：',
    'upload.audio': '🎵 音频：MP3, WAV, M4A, FLAC, OGG',
    'upload.video': '🎬 视频：MP4, AVI, MOV, MKV, WMV, FLV, WEBM',
    'upload.maxsize': '最大文件大小：',
    'upload.format_error': '不支持的文件格式。支持的格式：MP3, WAV, M4A, FLAC, OGG, MP4, AVI, MOV, MKV, WMV, FLV, WEBM',
    'upload.size_error': '文件大小超过限制。最大支持 {size}',
    'file.info': '文件大小: {size} • 类型: {type}',
    'file.type.audio': '音频',
    'file.type.video': '视频',
    'url.placeholder': '请输入直接音频文件URL（不支持视频平台链接）',
    'url.button': '处理音频',
    'url.processing': '正在处理...',
    'status.uploading': '正在上传文件...',
    'status.processing': '正在生成字幕...',
    'status.completed': '字幕生成完成',
    'error.no_file': '请先选择文件或输入音频URL',
    'error.no_config': '请先配置API设置',
    'translation.title': '翻译字幕',
    'translation.target': '目标语言',
    'translation.select_language': '选择翻译语言',
    'translation.translate': '开始翻译',
    'translation.translating': '翻译中...',
    'translation.success': '翻译完成',
    'translation.error': '翻译失败',
  },
  en: {
    'app.title': 'Subtitle Generator',
    'nav.settings': 'API Settings',
    'source.select': 'Select Audio/Video Source',
    'tab.local': 'Local File',
    'tab.online': 'Online Audio URL',
    'options.title': 'Processing Options',
    'options.source': 'Source Language',
    'options.translate': 'Translate Subtitles',
    'options.target': 'Target Language',
    'button.generate': 'Generate Subtitles',
    'button.processing': 'Processing...',
    'config.needed': 'API Configuration Required',
    'config.message': 'Please configure speech recognition and translation service API keys to start using.',
    'config.setup': 'Setup Now',
    'usage.title': 'Usage Instructions',
    'usage.quickstart': 'Quick Start',
    'usage.features': 'Features',
    'usage.step1': 'Click "API Settings" in the top right to configure speech recognition and translation APIs',
    'usage.step2': 'Upload audio/video file or enter online audio URL',
    'usage.step3': 'Select source language and translation options',
    'usage.step4': 'Click "Generate Subtitles" to start processing',
    'usage.step5': 'Edit subtitle content in preview area (optional)',
    'usage.step6': 'Download generated SRT files',
    'feature.audio': '🎵 Support multiple audio formats: MP3, WAV, M4A, FLAC, OGG',
    'feature.video': '🎬 Support multiple video formats: MP4, AVI, MOV, MKV, WMV',
    'feature.online': '🔗 Support online audio URL processing',
    'feature.preview': '📝 Complete subtitle preview and editing',
    'feature.translate': '🌐 Support multiple language translation',
    'feature.config': '⚙️ Flexible API configuration management',
    'feature.download': '💾 Support SRT format file download',
    'footer.copyright': 'Subtitle Generator ©{year} - Built with React + FastAPI',
    'upload.title': 'Click or drag files to this area to upload',
    'upload.support': 'Support single file upload, drag and drop supported',
    'upload.select': 'Select New File',
    'upload.error': 'Upload Error',
    'upload.format': 'Supported formats:',
    'upload.audio': '🎵 Audio: MP3, WAV, M4A, FLAC, OGG',
    'upload.video': '🎬 Video: MP4, AVI, MOV, MKV, WMV, FLV, WEBM',
    'upload.maxsize': 'Maximum file size:',
    'upload.format_error': 'Unsupported file format. Supported formats: MP3, WAV, M4A, FLAC, OGG, MP4, AVI, MOV, MKV, WMV, FLV, WEBM',
    'upload.size_error': 'File size exceeds limit. Maximum supported: {size}',
    'file.info': 'File size: {size} • Type: {type}',
    'file.type.audio': 'Audio',
    'file.type.video': 'Video',
    'url.placeholder': 'Enter direct audio file URL (video platform links not supported)',
    'url.button': 'Process Audio',
    'url.processing': 'Processing...',
    'status.uploading': 'Uploading file...',
    'status.processing': 'Generating subtitles...',
    'status.completed': 'Subtitle generation completed',
    'error.no_file': 'Please select a file or enter an audio URL first',
    'error.no_config': 'Please configure API settings first',
    'translation.title': 'Translate Subtitles',
    'translation.target': 'Target Language',
    'translation.select_language': 'Select translation language',
    'translation.translate': 'Start Translation',
    'translation.translating': 'Translating...',
    'translation.success': 'Translation completed',
    'translation.error': 'Translation failed',
  },
  'zh-TW': {
    'app.title': '得到字幕',
    'nav.settings': 'API 設定',
    'source.select': '選擇音視頻來源',
    'tab.local': '本地文件',
    'tab.online': '線上音頻URL',
    'options.title': '處理選項',
    'options.source': '來源語言',
    'options.translate': '翻譯字幕',
    'options.target': '目標語言',
    'button.generate': '產生字幕',
    'button.processing': '處理中...',
    'config.needed': '需要配置 API',
    'config.message': '請配置語音識別和翻譯服務的 API 金鑰以開始使用。',
    'config.setup': '立即配置',
    'usage.title': '使用說明',
    'usage.quickstart': '快速開始',
    'usage.features': '功能特性',
    'usage.step1': '點擊右上角「API 設定」配置語音識別和翻譯API',
    'usage.step2': '上傳音頻或視頻文件，或輸入線上音頻URL',
    'usage.step3': '選擇來源語言和翻譯選項',
    'usage.step4': '點擊「產生字幕」開始處理',
    'usage.step5': '在預覽區域編輯字幕內容（可選）',
    'usage.step6': '下載產生的SRT文件',
    'feature.audio': '🎵 支援多種音頻格式：MP3、WAV、M4A、FLAC、OGG',
    'feature.video': '🎬 支援多種視頻格式：MP4、AVI、MOV、MKV、WMV',
    'feature.online': '🔗 支援線上音頻URL處理',
    'feature.preview': '📝 完整字幕預覽和編輯功能',
    'feature.translate': '🌐 支援多種語言翻譯',
    'feature.config': '⚙️ 靈活的API配置管理',
    'feature.download': '💾 支援SRT格式文件下載',
    'footer.copyright': '得到字幕 ©{year} - 基於 React + FastAPI 構建',
    'upload.title': '點擊或拖拽文件到此區域上傳',
    'upload.support': '支援單個文件上傳，支援拖拽上傳',
    'upload.select': '重新選擇文件',
    'upload.error': '上傳錯誤',
    'upload.format': '支援的格式：',
    'upload.audio': '🎵 音頻：MP3, WAV, M4A, FLAC, OGG',
    'upload.video': '🎬 視頻：MP4, AVI, MOV, MKV, WMV, FLV, WEBM',
    'upload.maxsize': '最大文件大小：',
    'upload.format_error': '不支援的文件格式。支援的格式：MP3, WAV, M4A, FLAC, OGG, MP4, AVI, MOV, MKV, WMV, FLV, WEBM',
    'upload.size_error': '文件大小超過限制。最大支援 {size}',
    'file.info': '文件大小: {size} • 類型: {type}',
    'file.type.audio': '音頻',
    'file.type.video': '視頻',
    'url.placeholder': '請輸入直接音頻文件URL（不支援視頻平台連結）',
    'url.button': '處理音頻',
    'url.processing': '處理中...',
    'status.uploading': '正在上傳文件...',
    'status.processing': '正在產生字幕...',
    'status.completed': '字幕產生完成',
    'error.no_file': '請先選擇文件或輸入音頻URL',
    'error.no_config': '請先配置API設定',
  },
  ja: {
    'app.title': '字幕ジェネレーター',
    'nav.settings': 'API設定',
    'source.select': '音声/動画ソースを選択',
    'tab.local': 'ローカルファイル',
    'tab.online': 'オンライン音声URL',
    'options.title': '処理オプション',
    'options.source': '元の言語',
    'options.translate': '字幕翻訳',
    'options.target': 'ターゲット言語',
    'button.generate': '字幕生成',
    'button.processing': '処理中...',
    'config.needed': 'API設定が必要',
    'config.message': '音声認識と翻訳サービスのAPIキーを設定してください。',
    'config.setup': '今すぐ設定',
    'usage.title': '使用説明',
    'usage.quickstart': 'クイックスタート',
    'usage.features': '機能',
    'usage.step1': '右上の「API設定」をクリックして音声認識APIを設定',
    'usage.step2': '音声/動画ファイルをアップロード、またはオンライン音声URLを入力',
    'usage.step3': '元の言語と翻訳オプションを選択',
    'usage.step4': '「字幕生成」をクリックして処理開始',
    'usage.step5': 'プレビューエリアで字幕を編集（オプション）',
    'usage.step6': '生成されたSRTファイルをダウンロード',
    'feature.audio': '🎵 複数の音声形式をサポート：MP3、WAV、M4A、FLAC、OGG',
    'feature.video': '🎬 複数の動画形式をサポート：MP4、AVI、MOV、MKV、WMV',
    'feature.online': '🔗 オンライン音声URL処理をサポート',
    'feature.preview': '📝 完全な字幕プレビューと編集機能',
    'feature.translate': '🌐 複数言語翻訳をサポート',
    'feature.config': '⚙️ 柔軟なAPI設定管理',
    'feature.download': '💾 SRT形式ファイルダウンロードをサポート',
    'footer.copyright': '字幕ジェネレーター ©{year} - React + FastAPIで構築',
    'upload.title': 'ファイルをドラッグまたはクリックしてアップロード',
    'upload.support': '単一ファイルアップロードをサポート、ドラッグ＆ドロップ対応',
    'upload.select': '新しいファイルを選択',
    'upload.error': 'アップロードエラー',
    'upload.format': 'サポート形式：',
    'upload.audio': '🎵 音声：MP3、WAV、M4A、FLAC、OGG',
    'upload.video': '🎬 動画：MP4、AVI、MOV、MKV、WMV、FLV、WEBM',
    'upload.maxsize': '最大ファイルサイズ：',
    'upload.format_error': 'サポートされていないファイル形式。サポート形式：MP3、WAV、M4A、FLAC、OGG、MP4、AVI、MOV、MKV、WMV、FLV、WEBM',
    'upload.size_error': 'ファイルサイズが制限を超えています。最大サポートサイズ：{size}',
    'file.info': 'ファイルサイズ: {size} • タイプ: {type}',
    'file.type.audio': '音声',
    'file.type.video': '動画',
    'url.placeholder': '直接音声ファイルURLを入力（動画プラットフォームリンクは非サポート）',
    'url.button': '音声処理',
    'url.processing': '処理中...',
    'status.uploading': 'ファイルをアップロード中...',
    'status.processing': '字幕を生成中...',
    'status.completed': '字幕生成完了',
    'error.no_file': '最初にファイルを選択するか音声URLを入力してください',
    'error.no_config': '最初にAPI設定を構成してください',
    'translation.title': '字幕を翻訳',
    'translation.target': 'ターゲット言語',
    'translation.select_language': '翻訳言語を選択',
    'translation.translate': '翻訳開始',
    'translation.translating': '翻訳中...',
    'translation.success': '翻訳完了',
    'translation.error': '翻訳失敗',
  },
  ko: {
    'app.title': '자막 생성기',
    'nav.settings': 'API 설정',
    'source.select': '오디오/비디오 소스 선택',
    'tab.local': '로컬 파일',
    'tab.online': '온라인 비디오',
    'options.title': '처리 옵션',
    'options.source': '원본 언어',
    'options.translate': '자막 번역',
    'options.target': '대상 언어',
    'button.generate': '자막 생성',
    'button.processing': '처리 중...',
    'config.needed': 'API 설정 필요',
    'config.message': '음성 인식 및 번역 서비스 API 키를 설정해주세요.',
    'config.setup': '지금 설정',
    'usage.title': '사용 설명',
    'usage.quickstart': '빠른 시작',
    'usage.features': '기능',
    'usage.step1': '우측 상단의 "API 설정"을 클릭하여 음성 인식 API 설정',
    'usage.step2': '오디오 또는 비디오 파일 업로드',
    'usage.step3': '원본 언어 및 번역 옵션 선택',
    'usage.step4': '자막 생성"을 클릭하여 처리 시작',
    'usage.step5': '미리보기 영역에서 자막 편집 (선택 사항)',
    'usage.step6': '생성된 SRT 파일 다운로드',
    'feature.audio': '🎵 다양한 오디오 형식 지원: MP3, WAV, M4A, FLAC, OGG',
    'feature.video': '🎬 다양한 비디오 형식 지원: MP4, AVI, MOV, MKV, WMV',
    'feature.preview': '📝 완전한 자막 미리보기 및 편집 기능',
    'feature.translate': '🌐 다국어 번역 지원',
    'feature.config': '⚙️ 유연한 API 설정 관리',
    'feature.download': '💾 SRT 형식 파일 다운로드 지원',
    'footer.copyright': '자막 생성기 ©{year} - React + FastAPI로 구축',
    'upload.title': '파일을 드래그하거나 클릭하여 업로드',
    'upload.support': '단일 파일 업로드 지원, 드래그 앤 드롭 지원',
    'upload.select': '새 파일 선택',
    'upload.error': '업로드 오류',
    'upload.format': '지원 형식:',
    'upload.audio': '🎵 오디오: MP3, WAV, M4A, FLAC, OGG',
    'upload.video': '🎬 비디오: MP4, AVI, MOV, MKV, WMV, FLV, WEBM',
    'upload.maxsize': '최대 파일 크기:',
    'upload.format_error': '지원되지 않는 파일 형식. 지원 형식: MP3, WAV, M4A, FLAC, OGG, MP4, AVI, MOV, MKV, WMV, FLV, WEBM',
    'upload.size_error': '파일 크기가 제한을 초과했습니다. 최대 지원 크기: {size}',
    'file.info': '파일 크기: {size} • 유형: {type}',
    'file.type.audio': '오디오',
    'file.type.video': '비디오',
    'url.placeholder': '오디오/비디오 URL 입력 (YouTube, Bilibili 등 지원)',
    'url.button': '비디오 처리',
    'url.processing': '처리 중...',
    'status.uploading': '파일 업로드 중...',
    'status.processing': '자막 생성 중...',
    'status.completed': '자막 생성 완료',
    'error.no_file': '먼저 파일을 선택하거나 오디오/비디오 URL을 입력하세요',
    'error.no_config': '먼저 API 설정을 구성하세요',
    'translation.title': '자막 번역',
    'translation.target': '대상 언어',
    'translation.select_language': '번역 언어 선택',
    'translation.translate': '번역 시작',
    'translation.translating': '번역 중...',
    'translation.success': '번역 완료',
    'translation.error': '번역 실패',
  },
  fr: {
    'app.title': 'Générateur de Sous-titres',
    'nav.settings': 'Paramètres API',
    'source.select': 'Sélectionner la Source Audio/Vidéo',
    'tab.local': 'Fichier Local',
    'tab.online': 'Vidéo en Ligne',
    'options.title': 'Options de Traitement',
    'options.source': 'Langue Source',
    'options.translate': 'Traduire les Sous-titres',
    'options.target': 'Langue Cible',
    'button.generate': 'Générer des Sous-titres',
    'button.processing': 'Traitement en cours...',
    'config.needed': 'Configuration API Requise',
    'config.message': 'Veuillez configurer les clés API pour la reconnaissance vocale et la traduction.',
    'config.setup': 'Configurer Maintenant',
    'usage.title': 'Instructions d\'Utilisation',
    'usage.quickstart': 'Démarrage Rapide',
    'usage.features': 'Fonctionnalités',
    'usage.step1': 'Cliquez sur "Paramètres API" pour configurer les API de reconnaissance vocale',
    'usage.step2': 'Téléchargez un fichier audio ou vidéo',
    'usage.step3': 'Sélectionnez la langue source et les options de traduction',
    'usage.step4': 'Cliquez sur "Générer des Sous-titres" pour commencer',
    'usage.step5': 'Modifiez le contenu des sous-titres dans la zone de prévisualisation (optionnel)',
    'usage.step6': 'Téléchargez les fichiers SRT générés',
    'feature.audio': '🎵 Supporte plusieurs formats audio : MP3, WAV, M4A, FLAC, OGG',
    'feature.video': '🎬 Supporte plusieurs formats vidéo : MP4, AVI, MOV, MKV, WMV',
    'feature.preview': '📝 Prévisualisation et édition complètes des sous-titres',
    'feature.translate': '🌐 Supporte la traduction multilingue',
    'feature.config': '⚙️ Gestion flexible de la configuration API',
    'feature.download': '💾 Supporte le téléchargement de fichiers SRT',
    'footer.copyright': 'Générateur de Sous-titres ©{year} - Construit avec React + FastAPI',
    'upload.title': 'Cliquez ou glissez des fichiers dans cette zone',
    'upload.support': 'Supporte le téléchargement de fichier unique, glisser-déposer supporté',
    'upload.select': 'Sélectionner un Nouveau Fichier',
    'upload.error': 'Erreur de Téléchargement',
    'upload.format': 'Formats supportés :',
    'upload.audio': '🎵 Audio : MP3, WAV, M4A, FLAC, OGG',
    'upload.video': '🎬 Vidéo : MP4, AVI, MOV, MKV, WMV, FLV, WEBM',
    'upload.maxsize': 'Taille maximale du fichier :',
    'upload.format_error': 'Format de fichier non supporté. Formats supportés : MP3, WAV, M4A, FLAC, OGG, MP4, AVI, MOV, MKV, WMV, FLV, WEBM',
    'upload.size_error': 'La taille du fichier dépasse la limite. Maximum supporté : {size}',
    'file.info': 'Taille du fichier : {size} • Type : {type}',
    'file.type.audio': 'Audio',
    'file.type.video': 'Vidéo',
    'url.placeholder': 'Entrez l\'URL audio/vidéo (supporte YouTube, Bilibili, etc.)',
    'url.button': 'Traiter la Vidéo',
    'url.processing': 'Traitement en cours...',
    'status.uploading': 'Téléchargement du fichier...',
    'status.processing': 'Génération des sous-titres...',
    'status.completed': 'Génération des sous-titres terminée',
    'error.no_file': 'Veuillez d\'abord sélectionner un fichier ou entrer une URL audio/vidéo',
    'error.no_config': 'Veuillez d\'abord configurer les paramètres API',
    'translation.title': 'Traduire les Sous-titres',
    'translation.target': 'Langue Cible',
    'translation.select_language': 'Sélectionner la langue de traduction',
    'translation.translate': 'Commencer la traduction',
    'translation.translating': 'Traduction en cours...',
    'translation.success': 'Traduction terminée',
    'translation.error': 'Échec de la traduction',
  },
  de: {
    'app.title': 'Untertitel Generator',
    'nav.settings': 'API-Einstellungen',
    'source.select': 'Audio/Video-Quelle Auswählen',
    'tab.local': 'Lokale Datei',
    'tab.online': 'Online-Video',
    'options.title': 'Verarbeitungsoptionen',
    'options.source': 'Quellsprache',
    'options.translate': 'Untertitel Übersetzen',
    'options.target': 'Zielsprache',
    'button.generate': 'Untertitel Generieren',
    'button.processing': 'Verarbeitung...',
    'config.needed': 'API-Konfiguration Erforderlich',
    'config.message': 'Bitte konfigurieren Sie die API-Schlüssel für Spracherkennung und Übersetzung.',
    'config.setup': 'Jetzt Konfigurieren',
    'usage.title': 'Bedienungsanleitung',
    'usage.quickstart': 'Schnellstart',
    'usage.features': 'Funktionen',
    'usage.step1': 'Klicken Sie auf "API-Einstellungen" um Spracherkennungs-APIs zu konfigurieren',
    'usage.step2': 'Audio- oder Videodatei hochladen',
    'usage.step3': 'Quellsprache und Übersetzungsoptionen auswählen',
    'usage.step4': 'Klicken Sie auf "Untertitel Generieren" um zu starten',
    'usage.step5': 'Untertitelinhalt im Vorschau-Bereich bearbeiten (optional)',
    'usage.step6': 'Generierte SRT-Dateien herunterladen',
    'feature.audio': '🎵 Unterstützt mehrere Audioformate: MP3, WAV, M4A, FLAC, OGG',
    'feature.video': '🎬 Unterstützt mehrere Videoformate: MP4, AVI, MOV, MKV, WMV',
    'feature.preview': '📝 Vollständige Untertitel-Vorschau und Bearbeitung',
    'feature.translate': '🌐 Unterstützt mehrsprachige Übersetzung',
    'feature.config': '⚙️ Flexible API-Konfigurationsverwaltung',
    'feature.download': '💾 Unterstützt SRT-Datei-Downloads',
    'footer.copyright': 'Untertitel Generator ©{year} - Gebaut mit React + FastAPI',
    'upload.title': 'Klicken oder ziehen Sie Dateien in diesen Bereich',
    'upload.support': 'Unterstützt Einzel-Datei-Upload, Drag & Drop unterstützt',
    'upload.select': 'Neue Datei Auswählen',
    'upload.error': 'Upload-Fehler',
    'upload.format': 'Unterstützte Formate:',
    'upload.audio': '🎵 Audio: MP3, WAV, M4A, FLAC, OGG',
    'upload.video': '🎬 Video: MP4, AVI, MOV, MKV, WMV, FLV, WEBM',
    'upload.maxsize': 'Maximale Dateigröße:',
    'upload.format_error': 'Nicht unterstütztes Dateiformat. Unterstützte Formate: MP3, WAV, M4A, FLAC, OGG, MP4, AVI, MOV, MKV, WMV, FLV, WEBM',
    'upload.size_error': 'Dateigröße überschreitet das Limit. Maximal unterstützt: {size}',
    'file.info': 'Dateigröße: {size} • Typ: {type}',
    'file.type.audio': 'Audio',
    'file.type.video': 'Video',
    'url.placeholder': 'Audio/Video-URL eingeben (unterstützt YouTube, Bilibili, etc.)',
    'url.button': 'Video Verarbeiten',
    'url.processing': 'Verarbeitung...',
    'status.uploading': 'Datei wird hochgeladen...',
    'status.processing': 'Untertitel werden generiert...',
    'status.completed': 'Untertitel-Generierung abgeschlossen',
    'error.no_file': 'Bitte wählen Sie zuerst eine Datei aus oder geben Sie eine Audio/Video-URL ein',
    'error.no_config': 'Bitte konfigurieren Sie zuerst die API-Einstellungen',
    'translation.title': 'Untertitel Übersetzen',
    'translation.target': 'Zielsprache',
    'translation.select_language': 'Übersetzungssprache auswählen',
    'translation.translate': 'Übersetzung starten',
    'translation.translating': 'Übersetzung läuft...',
    'translation.success': 'Übersetzung abgeschlossen',
    'translation.error': 'Übersetzung fehlgeschlagen',
  },
  es: {
    'app.title': 'Generador de Subtítulos',
    'nav.settings': 'Configuración API',
    'source.select': 'Seleccionar Fuente Audio/Video',
    'tab.local': 'Archivo Local',
    'tab.online': 'Video en Línea',
    'options.title': 'Opciones de Procesamiento',
    'options.source': 'Idioma Original',
    'options.translate': 'Traducir Subtítulos',
    'options.target': 'Idioma Destino',
    'button.generate': 'Generar Subtítulos',
    'button.processing': 'Procesando...',
    'config.needed': 'Configuración API Requerida',
    'config.message': 'Por favor configure las claves API para reconocimiento de voz y traducción.',
    'config.setup': 'Configurar Ahora',
    'usage.title': 'Instrucciones de Uso',
    'usage.quickstart': 'Inicio Rápido',
    'usage.features': 'Características',
    'usage.step1': 'Haga clic en "Configuración API" para configurar las APIs de reconocimiento de voz',
    'usage.step2': 'Suba un archivo de audio o video',
    'usage.step3': 'Seleccione el idioma original y opciones de traducción',
    'usage.step4': 'Haga clic en "Generar Subtítulos" para comenzar',
    'usage.step5': 'Edite el contenido de los subtítulos en el área de vista previa (opcional)',
    'usage.step6': 'Descargue los archivos SRT generados',
    'feature.audio': '🎵 Soporta múltiples formatos de audio: MP3, WAV, M4A, FLAC, OGG',
    'feature.video': '🎬 Soporta múltiples formatos de video: MP4, AVI, MOV, MKV, WMV',
    'feature.preview': '📝 Vista previa y edición completa de subtítulos',
    'feature.translate': '🌐 Soporta traducción multilingüe',
    'feature.config': '⚙️ Gestión flexible de configuración API',
    'feature.download': '💾 Soporta descarga de archivos SRT',
    'footer.copyright': 'Generador de Subtítulos ©{year} - Construido con React + FastAPI',
    'upload.title': 'Haga clic o arrastre archivos a esta área',
    'upload.support': 'Soporta carga de archivo único, arrastrar y soltar soportado',
    'upload.select': 'Seleccionar Nuevo Archivo',
    'upload.error': 'Error de Carga',
    'upload.format': 'Formatos soportados:',
    'upload.audio': '🎵 Audio: MP3, WAV, M4A, FLAC, OGG',
    'upload.video': '🎬 Video: MP4, AVI, MOV, MKV, WMV, FLV, WEBM',
    'upload.maxsize': 'Tamaño máximo del archivo:',
    'upload.format_error': 'Formato de archivo no soportado. Formatos soportados: MP3, WAV, M4A, FLAC, OGG, MP4, AVI, MOV, MKV, WMV, FLV, WEBM',
    'upload.size_error': 'El tamaño del archivo excede el límite. Máximo soportado: {size}',
    'file.info': 'Tamaño del archivo: {size} • Tipo: {type}',
    'file.type.audio': 'Audio',
    'file.type.video': 'Video',
    'url.placeholder': 'Ingrese URL de audio/video (soporta YouTube, Bilibili, etc.)',
    'url.button': 'Procesar Video',
    'url.processing': 'Procesando...',
    'status.uploading': 'Subiendo archivo...',
    'status.processing': 'Generando subtítulos...',
    'status.completed': 'Generación de subtítulos completada',
    'error.no_file': 'Por favor seleccione primero un archivo o ingrese una URL de audio/video',
    'error.no_config': 'Por favor configure primero los ajustes API',
    'translation.title': 'Traducir Subtítulos',
    'translation.target': 'Idioma Destino',
    'translation.select_language': 'Seleccionar idioma de traducción',
    'translation.translate': 'Comenzar traducción',
    'translation.translating': 'Traduciendo...',
    'translation.success': 'Traducción completada',
    'translation.error': 'Error en la traducción',
  },
  it: {
    'app.title': 'Generatore di Sottotitoli',
    'nav.settings': 'Impostazioni API',
    'source.select': 'Seleziona Fonte Audio/Video',
    'tab.local': 'File Locale',
    'tab.online': 'Video Online',
    'options.title': 'Opzioni di Elaborazione',
    'options.source': 'Lingua Origine',
    'options.translate': 'Traduci Sottotitoli',
    'options.target': 'Lingua Destinazione',
    'button.generate': 'Genera Sottotitoli',
    'button.processing': 'Elaborazione...',
    'config.needed': 'Configurazione API Richiesta',
    'config.message': 'Per favore configura le chiavi API per il riconoscimento vocale e la traduzione.',
    'config.setup': 'Configura Ora',
    'usage.title': 'Istruzioni per l\'Uso',
    'usage.quickstart': 'Avvio Rapido',
    'usage.features': 'Funzionalità',
    'usage.step1': 'Fai clic su "Impostazioni API" per configurare le API di riconoscimento vocale',
    'usage.step2': 'Carica un file audio o video',
    'usage.step3': 'Seleziona la lingua origine e le opzioni di traduzione',
    'usage.step4': 'Fai clic su "Genera Sottotitoli" per iniziare',
    'usage.step5': 'Modifica il contenuto dei sottotitoli nell\'area di anteprima (opzionale)',
    'usage.step6': 'Scarica i file SRT generati',
    'feature.audio': '🎵 Supporta molteplici formati audio: MP3, WAV, M4A, FLAC, OGG',
    'feature.video': '🎬 Supporta molteplici formati video: MP4, AVI, MOV, MKV, WMV',
    'feature.preview': '📝 Anteprima e modifica completa dei sottotitoli',
    'feature.translate': '🌐 Supporta traduzione multilingue',
    'feature.config': '⚙️ Gestione flessibile della configurazione API',
    'feature.download': '💾 Supporta download di file SRT',
    'footer.copyright': 'Generatore di Sottotitoli ©{year} - Costruito con React + FastAPI',
    'upload.title': 'Fai clic o trascina i file in questa area',
    'upload.support': 'Supporta caricamento di file singolo, trascinamento supportato',
    'upload.select': 'Seleziona Nuovo File',
    'upload.error': 'Errore di Caricamento',
    'upload.format': 'Formati supportati:',
    'upload.audio': '🎵 Audio: MP3, WAV, M4A, FLAC, OGG',
    'upload.video': '🎬 Video: MP4, AVI, MOV, MKV, WMV, FLV, WEBM',
    'upload.maxsize': 'Dimensione massima file:',
    'upload.format_error': 'Formato file non supportato. Formati supportati: MP3, WAV, M4A, FLAC, OGG, MP4, AVI, MOV, MKV, WMV, FLV, WEBM',
    'upload.size_error': 'La dimensione del file supera il limite. Massimo supportato: {size}',
    'file.info': 'Dimensione file: {size} • Tipo: {type}',
    'file.type.audio': 'Audio',
    'file.type.video': 'Video',
    'url.placeholder': 'Inserisci URL audio/video (supporta YouTube, Bilibili, etc.)',
    'url.button': 'Elabora Video',
    'url.processing': 'Elaborazione...',
    'status.uploading': 'Caricamento file...',
    'status.processing': 'Generazione sottotitoli...',
    'status.completed': 'Generazione sottotitoli completata',
    'error.no_file': 'Per favore seleziona prima un file o inserisci un URL audio/video',
    'error.no_config': 'Per favore configura prima le impostazioni API',
    'translation.title': 'Traduci Sottotitoli',
    'translation.target': 'Lingua Destinazione',
    'translation.select_language': 'Seleziona lingua di traduzione',
    'translation.translate': 'Inizia traduzione',
    'translation.translating': 'Traduzione in corso...',
    'translation.success': 'Traduzione completata',
    'translation.error': 'Traduzione fallita',
  },
  pt: {
    'app.title': 'Gerador de Legendas',
    'nav.settings': 'Configurações API',
    'source.select': 'Selecionar Fonte Áudio/Vídeo',
    'tab.local': 'Arquivo Local',
    'tab.online': 'Vídeo Online',
    'options.title': 'Opções de Processamento',
    'options.source': 'Idioma Original',
    'options.translate': 'Traduzir Legendas',
    'options.target': 'Idioma Destino',
    'button.generate': 'Gerar Legendas',
    'button.processing': 'Processando...',
    'config.needed': 'Configuração API Necessária',
    'config.message': 'Por favor configure as chaves API para reconhecimento de voz e tradução.',
    'config.setup': 'Configurar Agora',
    'usage.title': 'Instruções de Uso',
    'usage.quickstart': 'Início Rápido',
    'usage.features': 'Recursos',
    'usage.step1': 'Clique em "Configurações API" para configurar as APIs de reconhecimento de voz',
    'usage.step2': 'Faça upload de um arquivo de áudio ou vídeo',
    'usage.step3': 'Selecione o idioma original e opções de tradução',
    'usage.step4': 'Clique em "Gerar Legendas" para começar',
    'usage.step5': 'Edite o conteúdo das legendas na área de visualização (opcional)',
    'usage.step6': 'Baixe os arquivos SRT gerados',
    'feature.audio': '🎵 Suporta múltiplos formatos de áudio: MP3, WAV, M4A, FLAC, OGG',
    'feature.video': '🎬 Suporta múltiplos formatos de vídeo: MP4, AVI, MOV, MKV, WMV',
    'feature.preview': '📝 Visualização e edição completa de legendas',
    'feature.translate': '🌐 Suporta tradução multilíngue',
    'feature.config': '⚙️ Gestão flexível de configuração API',
    'feature.download': '💾 Suporta download de arquivos SRT',
    'footer.copyright': 'Gerador de Legendas ©{year} - Construído com React + FastAPI',
    'upload.title': 'Clique ou arraste arquivos para esta área',
    'upload.support': 'Suporta upload de arquivo único, arrastar e soltar suportado',
    'upload.select': 'Selecionar Novo Arquivo',
    'upload.error': 'Erro de Upload',
    'upload.format': 'Formatos suportados:',
    'upload.audio': '🎵 Áudio: MP3, WAV, M4A, FLAC, OGG',
    'upload.video': '🎬 Vídeo: MP4, AVI, MOV, MKV, WMV, FLV, WEBM',
    'upload.maxsize': 'Tamanho máximo do arquivo:',
    'upload.format_error': 'Formato de arquivo não suportado. Formatos suportados: MP3, WAV, M4A, FLAC, OGG, MP4, AVI, MOV, MKV, WMV, FLV, WEBM',
    'upload.size_error': 'O tamanho do arquivo excede o limite. Máximo suportado: {size}',
    'file.info': 'Tamanho do arquivo: {size} • Tipo: {type}',
    'file.type.audio': 'Áudio',
    'file.type.video': 'Vídeo',
    'url.placeholder': 'Digite a URL áudio/vídeo (suporta YouTube, Bilibili, etc.)',
    'url.button': 'Processar Vídeo',
    'url.processing': 'Processando...',
    'status.uploading': 'Enviando arquivo...',
    'status.processing': 'Gerando legendas...',
    'status.completed': 'Geração de legendas concluída',
    'error.no_file': 'Por favor selecione primeiro um arquivo ou digite uma URL áudio/vídeo',
    'error.no_config': 'Por favor configure primeiro as configurações API',
    'translation.title': 'Traduzir Legendas',
    'translation.target': 'Idioma Destino',
    'translation.select_language': 'Selecionar idioma de tradução',
    'translation.translate': 'Começar tradução',
    'translation.translating': 'Traduzindo...',
    'translation.success': 'Tradução concluída',
    'translation.error': 'Falha na tradução',
  },
  ru: {
    'app.title': 'Генератор Субтитров',
    'nav.settings': 'Настройки API',
    'source.select': 'Выбрать Источник Аудио/Видео',
    'tab.local': 'Локальный Файл',
    'tab.online': 'Онлайн Видео',
    'options.title': 'Опции Обработки',
    'options.source': 'Исходный Язык',
    'options.translate': 'Перевести Субтитры',
    'options.target': 'Целевой Язык',
    'button.generate': 'Генерировать Субтитры',
    'button.processing': 'Обработка...',
    'config.needed': 'Требуется Конфигурация API',
    'config.message': 'Пожалуйста, настройте ключи API для распознавания речи и перевода.',
    'config.setup': 'Настроить Сейчас',
    'usage.title': 'Инструкции по Использованию',
    'usage.quickstart': 'Быстрый Старт',
    'usage.features': 'Функции',
    'usage.step1': 'Нажмите "Настройки API" для настройки API распознавания речи',
    'usage.step2': 'Загрузите аудио или видеофайл',
    'usage.step3': 'Выберите исходный язык и опции перевода',
    'usage.step4': 'Нажмите "Генерировать Субтитры" для начала',
    'usage.step5': 'Отредактируйте содержимое субтитров в области предварительного просмотра (опционально)',
    'usage.step6': 'Скачайте сгенерированные SRT файлы',
    'feature.audio': '🎵 Поддерживает множество аудиоформатов: MP3, WAV, M4A, FLAC, OGG',
    'feature.video': '🎬 Поддерживает множество видеоформатов: MP4, AVI, MOV, MKV, WMV',
    'feature.preview': '📝 Полный просмотр и редактирование субтитров',
    'feature.translate': '🌐 Поддерживает многоязычный перевод',
    'feature.config': '⚙️ Гибкое управление конфигурацией API',
    'feature.download': '💾 Поддерживает загрузку файлов SRT',
    'footer.copyright': 'Генератор Субтитров ©{year} - Построен на React + FastAPI',
    'upload.title': 'Нажмите или перетащите файлы в эту область',
    'upload.support': 'Поддерживает загрузку одного файла, перетаскивание поддерживается',
    'upload.select': 'Выбрать Новый Файл',
    'upload.error': 'Ошибка Загрузки',
    'upload.format': 'Поддерживаемые форматы:',
    'upload.audio': '🎵 Аудио: MP3, WAV, M4A, FLAC, OGG',
    'upload.video': '🎬 Видео: MP4, AVI, MOV, MKV, WMV, FLV, WEBM',
    'upload.maxsize': 'Максимальный размер файла:',
    'upload.format_error': 'Неподдерживаемый формат файла. Поддерживаемые форматы: MP3, WAV, M4A, FLAC, OGG, MP4, AVI, MOV, MKV, WMV, FLV, WEBM',
    'upload.size_error': 'Размер файла превышает лимит. Максимально поддерживается: {size}',
    'file.info': 'Размер файла: {size} • Тип: {type}',
    'file.type.audio': 'Аудио',
    'file.type.video': 'Видео',
    'url.placeholder': 'Введите URL аудио/видео (поддерживает YouTube, Bilibili и т.д.)',
    'url.button': 'Обработать Видео',
    'url.processing': 'Обработка...',
    'status.uploading': 'Загрузка файла...',
    'status.processing': 'Генерация субтитров...',
    'status.completed': 'Генерация субтитров завершена',
    'error.no_file': 'Пожалуйста, сначала выберите файл или введите URL аудио/видео',
    'error.no_config': 'Пожалуйста, сначала настройте параметры API',
    'translation.title': 'Перевести Субтитры',
    'translation.target': 'Целевой Язык',
    'translation.select_language': 'Выбрать язык перевода',
    'translation.translate': 'Начать перевод',
    'translation.translating': 'Перевод...',
    'translation.success': 'Перевод завершен',
    'translation.error': 'Ошибка перевода',
  },
  ar: {
    'app.title': 'مولد الترجمات',
    'nav.settings': 'إعدادات API',
    'source.select': 'اختر مصدر الصوت/الفيديو',
    'tab.local': 'ملف محلي',
    'tab.online': 'فيديو أونلاين',
    'options.title': 'خيارات المعالجة',
    'options.source': 'اللغة الأصلية',
    'options.translate': 'ترجمة الترجمات',
    'options.target': 'اللغة المستهدفة',
    'button.generate': 'إنشاء ترجمات',
    'button.processing': 'جاري المعالجة...',
    'config.needed': 'تكوين API مطلوب',
    'config.message': 'يرجى تكوين مفاتيح API للتعرف على الكلام والترجمة.',
    'config.setup': 'تكوين الآن',
    'usage.title': 'تعليمات الاستخدام',
    'usage.quickstart': 'بداية سريعة',
    'usage.features': 'الميزات',
    'usage.step1': 'انقر على "إعدادات API" لتكوين واجهات برمجة التعرف على الكلام',
    'usage.step2': 'ارفع ملف صوتي أو فيديو',
    'usage.step3': 'اختر اللغة الأصلية وخيارات الترجمة',
    'usage.step4': 'انقر على "إنشاء ترجمات" للبدء',
    'usage.step5': 'عدل محتوى الترجمات في منطقة المعاينة (اختياري)',
    'usage.step6': 'حمل ملفات SRT المولدة',
    'feature.audio': '🎵 يدعم العديد من صيغ الصوت: MP3, WAV, M4A, FLAC, OGG',
    'feature.video': '🎬 يدعم العديد من صيغ الفيديو: MP4, AVI, MOV, MKV, WMV',
    'feature.preview': '📝 معاينة وتحرير كامل للترجمات',
    'feature.translate': '🌐 يدعم الترجمة متعددة اللغات',
    'feature.config': '⚙️ إدارة مرنة لتكوين API',
    'feature.download': '💾 يدعم تحميل ملفات SRT',
    'footer.copyright': 'مولد الترجمات ©{year} - مبني باستخدام React + FastAPI',
    'upload.title': 'انقر أو اسحب الملفات إلى هذه المنطقة',
    'upload.support': 'يدعم رفع ملف واحد، السحب والإفلات مدعوم',
    'upload.select': 'اختر ملف جديد',
    'upload.error': 'خطأ في الرفع',
    'upload.format': 'الصيغ المدعومة:',
    'upload.audio': '🎵 صوت: MP3, WAV, M4A, FLAC, OGG',
    'upload.video': '🎬 فيديو: MP4, AVI, MOV, MKV, WMV, FLV, WEBM',
    'upload.maxsize': 'الحد الأقصى لحجم الملف:',
    'upload.format_error': 'صيغة ملف غير مدعومة. الصيغ المدعومة: MP3, WAV, M4A, FLAC, OGG, MP4, AVI, MOV, MKV, WMV, FLV, WEBM',
    'upload.size_error': 'حجم الملف يتجاوز الحد الأقصى. الحد الأقصى المدعوم: {size}',
    'file.info': 'حجم الملف: {size} • النوع: {type}',
    'file.type.audio': 'صوت',
    'file.type.video': 'فيديو',
    'url.placeholder': 'أدخل URL الصوت/الفيديو (يدعم YouTube, Bilibili, etc.)',
    'url.button': 'معالجة الفيديو',
    'url.processing': 'جاري المعالجة...',
    'status.uploading': 'جاري رفع الملف...',
    'status.processing': 'جاري إنشاء الترجمات...',
    'status.completed': 'اكتمل إنشاء الترجمات',
    'error.no_file': 'يرجى اختيار ملف أولاً أو إدخال URL صوت/فيديو',
    'error.no_config': 'يرجى تكوين إعدادات API أولاً',
    'translation.title': 'ترجمة الترجمات',
    'translation.target': 'اللغة المستهدفة',
    'translation.select_language': 'اختر لغة الترجمة',
    'translation.translate': 'ابدأ الترجمة',
    'translation.translating': 'جاري الترجمة...',
    'translation.success': 'اكتملت الترجمة',
    'translation.error': 'فشلت الترجمة',
  },
  hi: {
    'app.title': 'सबटाइटल जनरेटर',
    'nav.settings': 'API सेटिंग्स',
    'source.select': 'ऑडियो/वीडियो स्रोत चुनें',
    'tab.local': 'लोकल फाइल',
    'tab.online': 'ऑनलाइन वीडियो',
    'options.title': 'प्रोसेसिंग विकल्प',
    'options.source': 'सोर्स भाषा',
    'options.translate': 'सबटाइटल अनुवाद करें',
    'options.target': 'टारगेट भाषा',
    'button.generate': 'सबटाइटल जनरेट करें',
    'button.processing': 'प्रोसेसिंग...',
    'config.needed': 'API कॉन्फ़िगरेशन आवश्यक',
    'config.message': 'कृपया स्पीच रिकॉग्निशन और ट्रांसलेशन सर्विस की API कुंजियाँ कॉन्फ़िगर करें।',
    'config.setup': 'अभी कॉन्फ़िगर करें',
    'usage.title': 'उपयोग निर्देश',
    'usage.quickstart': 'त्वरित शुरुआत',
    'usage.features': 'विशेषताएं',
    'usage.step1': 'स्पीच रिकॉग्निशन API कॉन्फ़िगर करने के लिए "API सेटिंग्स" पर क्लिक करें',
    'usage.step2': 'ऑडियो या वीडियो फाइल अपलोड करें',
    'usage.step3': 'सोर्स भाषा और ट्रांसलेशन विकल्प चुनें',
    'usage.step4': 'शुरू करने के लिए "सबटाइटल जनरेट करें" पर क्लिक करें',
    'usage.step5': 'प्रीव्यू एरिया में सबटाइटल कंटेंट एडिट करें (वैकल्पिक)',
    'usage.step6': 'जनरेट की गई SRT फाइलें डाउनलोड करें',
    'feature.audio': '🎵 कई ऑडियो फॉर्मैट सपोर्ट करता है: MP3, WAV, M4A, FLAC, OGG',
    'feature.video': '🎬 कई वीडियो फॉर्मैट सपोर्ट करता है: MP4, AVI, MOV, MKV, WMV',
    'feature.preview': '📝 पूर्ण सबटाइटल प्रीव्यू और एडिटिंग',
    'feature.translate': '🌐 मल्टीलिंगुअल ट्रांसलेशन सपोर्ट करता है',
    'feature.config': '⚙️ फ्लेक्सिबल API कॉन्फ़िगरेशन मैनेजमेंट',
    'feature.download': '💾 SRT फॉर्मैट फाइल डाउनलोड सपोर्ट करता है',
    'footer.copyright': 'सबटाइटल जनरेटर ©{year} - React + FastAPI से बनाया गया',
    'upload.title': 'फाइलों को इस एरिया में अपलोड करने के लिए क्लिक या ड्रैग करें',
    'upload.support': 'सिंगल फाइल अपलोड सपोर्ट करता है, ड्रैग एंड ड्रॉप सपोर्टेड',
    'upload.select': 'नई फाइल चुनें',
    'upload.error': 'अपलोड एरर',
    'upload.format': 'सपोर्टेड फॉर्मैट:',
    'upload.audio': '🎵 ऑडियो: MP3, WAV, M4A, FLAC, OGG',
    'upload.video': '🎬 वीडियो: MP4, AVI, MOV, MKV, WMV, FLV, WEBM',
    'upload.maxsize': 'अधिकतम फाइल साइज:',
    'upload.format_error': 'असपोर्टेड फाइल फॉर्मैट। सपोर्टेड फॉर्मैट: MP3, WAV, M4A, FLAC, OGG, MP4, AVI, MOV, MKV, WMV, FLV, WEBM',
    'upload.size_error': 'फाइल साइज लिमिट से ज्यादा है। अधिकतम सपोर्टेड: {size}',
    'file.info': 'फाइल साइज: {size} • टाइप: {type}',
    'file.type.audio': 'ऑडियो',
    'file.type.video': 'वीडियो',
    'url.placeholder': 'ऑडियो/वीडियो URL डालें (YouTube, Bilibili आदि सपोर्ट करता है)',
    'url.button': 'वीडियो प्रोसेस करें',
    'url.processing': 'प्रोसेसिंग...',
    'status.uploading': 'फाइल अपलोड हो रही है...',
    'status.processing': 'सबटाइटल जनरेट हो रहे हैं...',
    'status.completed': 'सबटाइटल जनरेशन पूर्ण',
    'error.no_file': 'कृपया पहले एक फाइल चुनें या ऑडियो/वीडियो URL डालें',
    'error.no_config': 'कृपया पहले API सेटिंग्स कॉन्फ़िगर करें',
    'translation.title': 'सबटाइटल अनुवाद करें',
    'translation.target': 'टारगेट भाषा',
    'translation.select_language': 'अनुवाद भाषा चुनें',
    'translation.translate': 'अनुवाद शुरू करें',
    'translation.translating': 'अनुवाद हो रहा है...',
    'translation.success': 'अनुवाद पूर्ण',
    'translation.error': 'अनुवाद विफल',
  },
  th: {
    'app.title': 'ตัวสร้างคำบรรยาย',
    'nav.settings': 'ตั้งค่า API',
    'source.select': 'เลือกแหล่งที่มาเสียง/วิดีโอ',
    'tab.local': 'ไฟล์ในเครื่อง',
    'tab.online': 'วิดีโอออนไลน์',
    'options.title': 'ตัวเลือกการประมวลผล',
    'options.source': 'ภาษาต้นฉบับ',
    'options.translate': 'แปลคำบรรยาย',
    'options.target': 'ภาษาเป้าหมาย',
    'button.generate': 'สร้างคำบรรยาย',
    'button.processing': 'กำลังประมวลผล...',
    'config.needed': 'ต้องการการตั้งค่า API',
    'config.message': 'กรุณาตั้งค่าคีย์ API สำหรับการรู้จำเสียงพูดและการแปลภาษา',
    'config.setup': 'ตั้งค่าตอนนี้',
    'usage.title': 'คำแนะนำการใช้งาน',
    'usage.quickstart': 'เริ่มต้นอย่างรวดเร็ว',
    'usage.features': 'คุณสมบัติ',
    'usage.step1': 'คลิก "ตั้งค่า API" เพื่อตั้งค่า API การรู้จำเสียงพูด',
    'usage.step2': 'อัปโหลดไฟล์เสียงหรือวิดีโอ',
    'usage.step3': 'เลือกภาษาต้นฉบับและตัวเลือกการแปล',
    'usage.step4': 'คลิก "สร้างคำบรรยาย" เพื่อเริ่มต้น',
    'usage.step5': 'แก้ไขเนื้อหาคำบรรยายในพื้นที่แสดงตัวอย่าง (ไม่บังคับ)',
    'usage.step6': 'ดาวน์โหลดไฟล์ SRT ที่สร้างขึ้น',
    'feature.audio': '🎵 รองรับหลายรูปแบบเสียง: MP3, WAV, M4A, FLAC, OGG',
    'feature.video': '🎬 รองรับหลายรูปแบบวิดีโอ: MP4, AVI, MOV, MKV, WMV',
    'feature.preview': '📝 การแสดงตัวอย่างและแก้ไขคำบรรยายแบบเต็มรูปแบบ',
    'feature.translate': '🌐 รองรับการแปลหลายภาษา',
    'feature.config': '⚙️ การจัดการการตั้งค่า API ที่ยืดหยุ่น',
    'feature.download': '💾 รองรับการดาวน์โหลดไฟล์ SRT',
    'footer.copyright': 'ตัวสร้างคำบรรยาย ©{year} - สร้างด้วย React + FastAPI',
    'upload.title': 'คลิกหรือลากไฟล์มายังพื้นที่นี้เพื่ออัปโหลด',
    'upload.support': 'รองรับการอัปโหลดไฟล์เดี่ยว รองรับการลากและวาง',
    'upload.select': 'เลือกไฟล์ใหม่',
    'upload.error': 'ข้อผิดพลาดในการอัปโหลด',
    'upload.format': 'รูปแบบที่รองรับ:',
    'upload.audio': '🎵 เสียง: MP3, WAV, M4A, FLAC, OGG',
    'upload.video': '🎬 วิดีโอ: MP4, AVI, MOV, MKV, WMV, FLV, WEBM',
    'upload.maxsize': 'ขนาดไฟล์สูงสุด:',
    'upload.format_error': 'รูปแบบไฟล์ไม่รองรับ รูปแบบที่รองรับ: MP3, WAV, M4A, FLAC, OGG, MP4, AVI, MOV, MKV, WMV, FLV, WEBM',
    'upload.size_error': 'ขนาดไฟล์เกินขีดจำกัด สูงสุดที่รองรับ: {size}',
    'file.info': 'ขนาดไฟล์: {size} • ประเภท: {type}',
    'file.type.audio': 'เสียง',
    'file.type.video': 'วิดีโอ',
    'url.placeholder': 'ป้อน URL เสียง/วิดีโอ (รองรับ YouTube, Bilibili ฯลฯ)',
    'url.button': 'ประมวลผลวิดีโอ',
    'url.processing': 'กำลังประมวลผล...',
    'status.uploading': 'กำลังอัปโหลดไฟล์...',
    'status.processing': 'กำลังสร้างคำบรรยาย...',
    'status.completed': 'การสร้างคำบรรยายเสร็จสมบูรณ์',
    'error.no_file': 'กรุณาเลือกไฟล์ก่อนหรือป้อน URL เสียง/วิดีโอ',
    'error.no_config': 'กรุณาตั้งค่า API ก่อน',
    'translation.title': 'แปลคำบรรยาย',
    'translation.target': 'ภาษาเป้าหมาย',
    'translation.select_language': 'เลือกภาษาที่จะแปล',
    'translation.translate': 'เริ่มการแปล',
    'translation.translating': 'กำลังแปล...',
    'translation.success': 'การแปลเสร็จสมบูรณ์',
    'translation.error': 'การแปลล้มเหลว',
  },
  vi: {
    'app.title': 'Trình Tạo Phụ Đề',
    'nav.settings': 'Cài đặt API',
    'source.select': 'Chọn Nguồn Âm thanh/Video',
    'tab.local': 'Tệp Cục bộ',
    'tab.online': 'Video Trực tuyến',
    'options.title': 'Tùy chọn Xử lý',
    'options.source': 'Ngôn ngữ Nguồn',
    'options.translate': 'Dịch Phụ đề',
    'options.target': 'Ngôn ngữ Đích',
    'button.generate': 'Tạo Phụ đề',
    'button.processing': 'Đang xử lý...',
    'config.needed': 'Cần Cấu hình API',
    'config.message': 'Vui lòng cấu hình khóa API cho nhận dạng giọng nói và dịch thuật.',
    'config.setup': 'Cấu hình Ngay',
    'usage.title': 'Hướng dẫn Sử dụng',
    'usage.quickstart': 'Khởi động Nhanh',
    'usage.features': 'Tính năng',
    'usage.step1': 'Nhấp vào "Cài đặt API" để cấu hình API nhận dạng giọng nói',
    'usage.step2': 'Tải lên tệp âm thanh hoặc video',
    'usage.step3': 'Chọn ngôn ngữ nguồn và tùy chọn dịch thuật',
    'usage.step4': 'Nhấp vào "Tạo Phụ đề" để bắt đầu',
    'usage.step5': 'Chỉnh sửa nội dung phụ đề trong khu vực xem trước (tùy chọn)',
    'usage.step6': 'Tải xuống các tệp SRT đã tạo',
    'feature.audio': '🎵 Hỗ trợ nhiều định dạng âm thanh: MP3, WAV, M4A, FLAC, OGG',
    'feature.video': '🎬 Hỗ trợ nhiều định dạng video: MP4, AVI, MOV, MKV, WMV',
    'feature.preview': '📝 Xem trước và chỉnh sửa phụ đề đầy đủ',
    'feature.translate': '🌐 Hỗ trợ dịch thuật đa ngôn ngữ',
    'feature.config': '⚙️ Quản lý cấu hình API linh hoạt',
    'feature.download': '💾 Hỗ trợ tải xuống tệp SRT',
    'footer.copyright': 'Trình Tạo Phụ đề ©{year} - Xây dựng bằng React + FastAPI',
    'upload.title': 'Nhấp hoặc kéo tệp vào khu vực này để tải lên',
    'upload.support': 'Hỗ trợ tải lên tệp đơn, hỗ trợ kéo và thả',
    'upload.select': 'Chọn Tệp Mới',
    'upload.error': 'Lỗi Tải lên',
    'upload.format': 'Định dạng được hỗ trợ:',
    'upload.audio': '🎵 Âm thanh: MP3, WAV, M4A, FLAC, OGG',
    'upload.video': '🎬 Video: MP4, AVI, MOV, MKV, WMV, FLV, WEBM',
    'upload.maxsize': 'Kích thước tệp tối đa:',
    'upload.format_error': 'Định dạng tệp không được hỗ trợ. Định dạng được hỗ trợ: MP3, WAV, M4A, FLAC, OGG, MP4, AVI, MOV, MKV, WMV, FLV, WEBM',
    'upload.size_error': 'Kích thước tệp vượt quá giới hạn. Tối đa được hỗ trợ: {size}',
    'file.info': 'Kích thước tệp: {size} • Loại: {type}',
    'file.type.audio': 'Âm thanh',
    'file.type.video': 'Video',
    'url.placeholder': 'Nhập URL âm thanh/video (hỗ trợ YouTube, Bilibili, v.v.)',
    'url.button': 'Xử lý Video',
    'url.processing': 'Đang xử lý...',
    'status.uploading': 'Đang tải lên tệp...',
    'status.processing': 'Đang tạo phụ đề...',
    'status.completed': 'Hoàn thành tạo phụ đề',
    'error.no_file': 'Vui lòng chọn tệp trước hoặc nhập URL âm thanh/video',
    'error.no_config': 'Vui lòng cấu hình cài đặt API trước',
    'translation.title': 'Dịch Phụ đề',
    'translation.target': 'Ngôn ngữ Đích',
    'translation.select_language': 'Chọn ngôn ngữ dịch',
    'translation.translate': 'Bắt đầu dịch',
    'translation.translating': 'Đang dịch...',
    'translation.success': 'Dịch hoàn tất',
    'translation.error': 'Dịch thất bại',
  },
  tr: {
    'app.title': 'Altyazı Oluşturucu',
    'nav.settings': 'API Ayarları',
    'source.select': 'Ses/Video Kaynağı Seç',
    'tab.local': 'Yerel Dosya',
    'tab.online': 'Çevrimiçi Video',
    'options.title': 'İşleme Seçenekleri',
    'options.source': 'Kaynak Dil',
    'options.translate': 'Altyazıları Çevir',
    'options.target': 'Hedef Dil',
    'button.generate': 'Altyazı Oluştur',
    'button.processing': 'İşleniyor...',
    'config.needed': 'API Yapılandırması Gerekli',
    'config.message': 'Lütfen konuşma tanıma ve çeviri hizmetleri için API anahtarlarını yapılandırın.',
    'config.setup': 'Şimdi Yapılandır',
    'usage.title': 'Kullanım Talimatları',
    'usage.quickstart': 'Hızlı Başlangıç',
    'usage.features': 'Özellikler',
    'usage.step1': 'Konuşma tanıma API\'lerini yapılandırmak için "API Ayarları"nı tıklayın',
    'usage.step2': 'Ses veya video dosyası yükleyin',
    'usage.step3': 'Kaynak dili ve çeviri seçeneklerini seçin',
    'usage.step4': 'Başlamak için "Altyazı Oluştur"u tıklayın',
    'usage.step5': 'Önizleme alanında altyazı içeriğini düzenleyin (isteğe bağlı)',
    'usage.step6': 'Oluşturulan SRT dosyalarını indirin',
    'feature.audio': '🎵 Birden fazla ses formatını destekler: MP3, WAV, M4A, FLAC, OGG',
    'feature.video': '🎬 Birden fazla video formatını destekler: MP4, AVI, MOV, MKV, WMV',
    'feature.preview': '📝 Tam altyazı önizleme ve düzenleme',
    'feature.translate': '🌐 Çok dilli çeviri desteği',
    'feature.config': '⚙️ Esnek API yapılandırma yönetimi',
    'feature.download': '💾 SRT dosyası indirme desteği',
    'footer.copyright': 'Altyazı Oluşturucu ©{year} - React + FastAPI ile oluşturuldu',
    'upload.title': 'Dosyaları bu alana yüklemek için tıklayın veya sürükleyin',
    'upload.support': 'Tek dosya yüklemeyi destekler, sürükle ve bırak desteklenir',
    'upload.select': 'Yeni Dosya Seç',
    'upload.error': 'Yükleme Hatası',
    'upload.format': 'Desteklenen formatlar:',
    'upload.audio': '🎵 Ses: MP3, WAV, M4A, FLAC, OGG',
    'upload.video': '🎬 Video: MP4, AVI, MOV, MKV, WMV, FLV, WEBM',
    'upload.maxsize': 'Maksimum dosya boyutu:',
    'upload.format_error': 'Desteklenmeyen dosya formatı. Desteklenen formatlar: MP3, WAV, M4A, FLAC, OGG, MP4, AVI, MOV, MKV, WMV, FLV, WEBM',
    'upload.size_error': 'Dosya boyutu limiti aşıyor. Maksimum desteklenen: {size}',
    'file.info': 'Dosya boyutu: {size} • Tür: {type}',
    'file.type.audio': 'Ses',
    'file.type.video': 'Video',
    'url.placeholder': 'Ses/video URL\'si girin (YouTube, Bilibili vb. destekler)',
    'url.button': 'Videoyu İşle',
    'url.processing': 'İşleniyor...',
    'status.uploading': 'Dosya yükleniyor...',
    'status.processing': 'Altyazılar oluşturuluyor...',
    'status.completed': 'Altyazı oluşturma tamamlandı',
    'error.no_file': 'Lütfen önce bir dosya seçin veya ses/video URL\'si girin',
    'error.no_config': 'Lütfen önce API ayarlarını yapılandırın',
    'translation.title': 'Altyazıları Çevir',
    'translation.target': 'Hedef Dil',
    'translation.select_language': 'Çeviri dili seçin',
    'translation.translate': 'Çeviriyi başlat',
    'translation.translating': 'Çeviri yapılıyor...',
    'translation.success': 'Çeviri tamamlandı',
    'translation.error': 'Çeviri başarısız',
  }
};

const ThemeContext = createContext<ThemeContextType | undefined>(undefined);

export const useTheme = () => {
  const context = useContext(ThemeContext);
  if (!context) {
    throw new Error('useTheme must be used within a ThemeProvider');
  }
  return context;
};

export const ThemeProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [theme, setTheme] = useState<Theme>(() => {
    const saved = localStorage.getItem('theme');
    return (saved as Theme) || 'light';
  });
  
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'zh';
  });

  useEffect(() => {
    localStorage.setItem('theme', theme);
    document.documentElement.setAttribute('data-theme', theme);
  }, [theme]);

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <ThemeContext.Provider value={{ theme, setTheme, language, setLanguage, t }}>
      {children}
    </ThemeContext.Provider>
  );
};